group/api/urls.py
from django.urls import path

from .views import (
                GroupListAPIView,
                GroupAddModeratorAPIView,
                GroupAddUserAPIView,
                GroupDemandModeratorAPIView,
                GroupDemandUserAPIView,
                GroupRemoveDemandUserAPIView,
                GroupRemoveDemandModeratorAPIView,
                GroupRemoveUserAPIView,
                )


app_name    = 'api-group'

urlpatterns = [
    path('list/', GroupListAPIView.as_view(), name='list'),#/api/group/list
    path('add/<str:username>/to/<str:name>/', GroupAddUserAPIView.as_view(), name='add_user'),#/api/group/add/username/to/group_name
    path('add/<str:username>/to_moderate/<str:name>/', GroupAddModeratorAPIView.as_view(), name='add_moderator'),#/api/group/add/username/to_moderate/group_name
    path('remove_demand/<str:username>/to/<str:name>/', GroupRemoveDemandUserAPIView.as_view(), name='remove_demand'),#/api/group/remove_demand/username/to/group_name
    path('remove_demand/<str:username>/to_moderate/<str:name>/', GroupRemoveDemandModeratorAPIView.as_view(), name='remove_demand_moderate'),#/api/group/remove_demand/username/to_moderate/group_name
    path('remove/<str:username>/from/<str:name>/', GroupRemoveUserAPIView.as_view(), name='remove_user'),#/api/group/remove/username/from/group_name
    path('demand/<str:username>/to/<str:name>/', GroupDemandUserAPIView.as_view(), name='demand'),#/api/group/demand/username/to/group_name
    path('demand/<str:username>/to_moderate/<str:name>/', GroupDemandModeratorAPIView.as_view(), name='demand_moderate'),#/api/group/demand/username/to_moderate/group_name
]

group/urls.py
from django.urls import path

from .views import (
                GroupDetailView
                )


app_name    = 'group'

urlpatterns = [
    path('<str:name>/', GroupDetailView.as_view(), name='detail'),#/group_name
]

rci/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from .views import home_view, SearchView
from account.views import UserRegisterView
from post.views import PostListView

urlpatterns = [
    path('', home_view, name='home'),
    path('home/', PostListView.as_view(), name='post-list'),
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name="search"),
    path('register/', UserRegisterView.as_view(), name="register"),
    path('post/', include('post.urls', namespace='post')),
    path('profile/', include('account.urls', namespace='profile')),
    path('group/', include('group.urls', namespace='group')),
    path('tag/', include('hashtag.urls', namespace='hashtag')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('api/post/',include('post.api.urls', namespace='api-post')),
    path('api/profile/',include('account.api.urls', namespace='api-profile')),
    path('api/group/',include('group.api.urls', namespace='api-group')),
    path('api/comment/',include('comment.api.urls', namespace='api-comment')),
    path('', include('django.contrib.auth.urls')),

    # path('api/hashtag/',include('hashtag.api.urls', namespace='api-hashtag')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


#the Manager of the Group Model
class GroupManager(models.Manager):

    def add_user(self, user, group):
        group.join_asks.remove(user)
        user.profile.groups.add(group)
        return user.profile in group.get_members()

    def remove_demand_user(self, user, group):
        group.join_asks.remove(user)
        return user.profile in group.get_members()

    def remove_user(self, user, group):
        user.profile.groups.remove(group)
        return user.profile in group.get_members()

    def ask_join_user(self, user, group):
        group.join_asks.add(user)
        return user.profile in group.get_members()

    def ask_moderators_user(self, user, group):
        group.moderators_asks.add(user)
        return user in group.get_moderators()

    def add_moderator(self, user, group):
        group.moderators_asks.remove(user)
        group.moderators.add(user)
        return user in group.get_moderators()

    def remove_demand_moderator(self, user, group):
        group.moderators_asks.remove(user)
        return user in group.get_moderators()


#Model group in database
class Group(models.Model):
    moderators          = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='moderator_of', default=1)#le modérateur du groupe
    join_asks           = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='ask_to_join', default=1, blank=True)#le les demandes d'accès au groupe
    moderators_asks     = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='ask_to_moderate', default=1, blank=True)#le les demandes de modérer le groupe

    name        = models.CharField(max_length=50, default='', unique=True)#name of the group
    description = models.CharField(max_length=200, default='')#description of the group
    timestamp   = models.DateTimeField(auto_now_add=True)# date of creation
    last_update_time    = models.DateTimeField(auto_now_add=True)# date of last update

    objects     = GroupManager()

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("group:detail", kwargs={'name':self.name})

    def get_members(self):#members is the related name of member_in in Profile
        return self.members.all()

    def get_moderators(self):
        return self.moderators.all()

    def get_join_asks(self):
        return self.join_asks.all()

    def get_moderators_asks(self):
        return self.moderators_asks.all()

    def has_moderator(self, user):
        return user in self.get_moderators()

group/api/views.py
# from django
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404

from rest_framework import generics, permissions
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView

from .pagination import GroupDisplayPagination
from .serializers import GroupModelSerializer
from group.models import Group

UserModel  = get_user_model()

#the api view
class GroupListAPIView(generics.ListAPIView):
    serializer_class    = GroupModelSerializer           # the serializer class we made in .serializers
    permission_classes  = [permissions.IsAuthenticated] #user must be authenticated
    pagination_class    = GroupDisplayPagination

    def get_queryset(self, *args, **kwargs):
        group_queryset = Group.objects.all().order_by('-timestamp')
        return group_queryset

#add a user to a group api view
class GroupAddUserAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if request.user in group.get_moderators():
                if user in group.get_join_asks():
                    if user.profile not in group.get_members():
                        user_member_in = Group.objects.add_user(user, group)
                        return Response({"user_member_in" : user_member_in})
                    return Response({"message" : "l'utilisateur est déja membre"}, status = 400 )
                return Response({"message" : "l'utilisateur n'a pas demandé l'ajout"}, status = 400 )
            return Response({"message" : "Vous n'êtes pas modérateur de ce groupe"}, status = 400 )
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupRemoveDemandUserAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if request.user in group.get_moderators():
                user_member_in = Group.objects.remove_demand_user(user, group)
                return Response({"user_member_in" : user_member_in})
            return Response({"message" : "Vous n'êtes pas modérateur de ce groupe"}, status = 400 )
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupRemoveUserAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if request.user in group.get_moderators():
                if user not in group.get_moderators():
                    if user.profile in group.get_members():
                        user_member_in = Group.objects.remove_user(user, group)
                        return Response({"user_member_in" : user_member_in})
                    return Response({"message" : "L'utilisateur n'est pas membre du groupe"})
                return Response({"message" : "L'utilisateur est un modérateur du groupe"})
            return Response({"message" : "Vous n'êtes pas modérateur de ce groupe"}, status = 400 )
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupDemandUserAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if user.profile not in group.get_members():
                if user.profile not in group.get_join_asks():
                    user_member_in = Group.objects.ask_join_user(user, group)
                    return Response({"user_member_in" : user_member_in})
                return Response({"message" : "Une demande d'ajout est déja en cours de traitement"})
            return Response({"message" : "L'utilisateur est déja membre du groupe"})
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupDemandModeratorAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if user.profile in group.get_members():
                if user not in group.get_moderators():
                    if user not in group.get_moderators_asks():
                        user_moderator_of = Group.objects.ask_moderators_user(user, group)
                        return Response({"user_moderator_of" : user_moderator_of})
                    return Response({"message" : "Une demande de modération est déja en cours de traitement"})
                return Response({"message" : "L'utilisateur est déja modérateur de ce groupe"})
            return Response({"message" : "L'utilisateur n'est même pas membre du groupe"})
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupAddModeratorAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if request.user in group.get_moderators():
                if user in group.get_moderators_asks():
                    if user.profile not in group.get_moderators():
                        user_moderator_of = Group.objects.add_moderator(user, group)
                        return Response({"user_moderator_of" : user_moderator_of})
                    return Response({"message" : "l'utilisateur est déja modérateur de ce groupe"}, status = 400 )
                return Response({"message" : "l'utilisateur n'a pas demandé l'ajout"}, status = 400 )
            return Response({"message" : "Vous n'êtes pas modérateur de ce groupe"}, status = 400 )
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

class GroupRemoveDemandModeratorAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]
    def get(self, request, format = None, *args, **kwargs):
        group_name  = self.kwargs.get('name')
        username    = self.kwargs.get('username')
        group       = get_object_or_404(Group, name=group_name)
        user        = get_object_or_404(UserModel, username=username)
        if request.user.is_authenticated:
            if request.user in group.get_moderators():
                user_moderator_of = Group.objects.remove_demand_moderator(user, group)
                return Response({"user_moderator_of" : user_moderator_of})
            return Response({"message" : "Vous n'êtes pas modérateur de ce groupe"}, status = 400 )
        return Response({"message" : "Vous êtes Anonyme"}, status = 400 )

group/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse

from .models import Group

from django.views.generic import (
                                ListView,
                                DetailView,
                                CreateView,
                                DeleteView
                                )
from post.forms import PostModelForm

#group detail view
class GroupDetailView(LoginRequiredMixin, DetailView):
    template_name = 'group/group_detail.html'
    login_url     = '/login'

    def get_object(self):
        group_name      = self.kwargs.get('name')
        return get_object_or_404(Group,name__iexact = group_name)

    def get_context_data(self, *args, **kwargs):                                        #override the method get_context
        group_name = self.kwargs.get('name')
        context                     = super(GroupDetailView,self).get_context_data(*args, **kwargs)    #previous context
        context['post_form']        = PostModelForm()                                   #the form to create post
        context['fetch_post_url']   = reverse_lazy('api-post:group', kwargs={'name':group_name})#where to fetch Data from API
        context['create_post_url']  = reverse_lazy('api-post:create')               #where to post Data to API when creating a post
        return context

rci/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, reverse
from django.views import View

from group.models import Group
from hashtag.models import Hashtag

User = get_user_model()

def home_view(request):

    return render(request,"home.html",{})
    # return render(request,"home.html",context)

class SearchView(LoginRequiredMixin, View):
    login_url   = '/login'
    def get(self, request, *args, **kwargs):
        query                   = request.GET.get("q")
        users_queryset    = None
        if query is not None:
            users_queryset    = User.objects.filter(
                                Q(username__icontains=query)
                                )
        groups_queryset    = None
        if query is not None:
            groups_queryset    = Group.objects.filter(
                                Q(name__icontains=query)
                                )
        hashtags_queryset    = None
        if query is not None:
            hashtags_queryset  = Hashtag.objects.filter(
                                Q(tag__icontains=query)
                                )

        context = {
            "users"                 : users_queryset,
            "groups"                : groups_queryset,
            "tags"                  : hashtags_queryset,
            "fetch_post_url"        : reverse("api-post:list"),
            }
        return render(request, "search.html", context)

rci/templates/group/group_ask_join_modal.html
<div class="modal fade" id="ask-join-modal"
 tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h5 class="modal-title" id="reply-form-header">Demandes d'ajout au groupe {{group_name}} :</h5>
          <hr>
        </div>

        <div class="modal-body">
          <ul class="list-group scroll-list">
          </h4> Demandes de la part de: </h4>
              </br></br>
              {% for user in group_join_asks %}
                <li class="list-group-item">
                    <div class="row">
                      <div class="col-sm-2 ">
                        <a href = "{{user.profile.get_absolute_url}}">
                          <div class="row">
                          		<div class="profile-header-img col-sm-2 ">
                                <img class="img-min" src="{{user.profile.get_img_url}}" />

                              </div>
                          </div>
                        </a>
                      </div>
                      <div class="col-sm-4 in-line">
                        <a href="{{user.profile.get_absolute_url}}"> {{user}} </a>
                        <div action-url="{% url 'api-group:add_user' username=user.username name=group_name %}" group-name="{{group_name}}" user-username="{{user.username}}">
                          <a href="#" class="group-access-management-btn hvr-grow" >
                            <i class="fa fa-check green-color" ></i>
                          </a>
                        </div>
                        <div action-url="{% url 'api-group:remove_demand' username=user.username name=group_name %}" group-name="{{group_name}}" user-username="{{user.username}}">
                          <a href="#" class="group-access-management-btn hvr-grow" >
                            <i class="fa fa-trash red-color" ></i>
                         </a>
                        </div>
                      </div>
                    </div>
                </li>
              {% endfor %}

          </ul>
        </div>





      </div>

    </div>
  </div>
</div>

rci/templates/group/group_ask_moderate_modal.html
<div class="modal fade" id="ask-moderate-modal"
 tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h5 class="modal-title" id="reply-form-header">Demandes de modération du groupe {{group_name}} :</h5>
          <hr>
        </div>

        <div class="modal-body">
          <ul class="list-group scroll-list">
          </h4> Demandes de la part de: </h4>
              </br></br>
              {% for user in group_moderators_asks %}
                <li class="list-group-item">
                    <div class="row">
                      <div class="col-sm-2 ">
                        <a href = "{{user.profile.get_absolute_url}}">
                          <div class="row">
                          		<div class="profile-header-img col-sm-2 ">
                                <img class="img-min" src="{{user.profile.get_img_url}}" />

                              </div>
                          </div>
                        </a>
                      </div>
                      <div class="col-sm-4 in-line">
                        <a href="{{user.profile.get_absolute_url}}"> {{user}} </a>
                        <div action-url="{% url 'api-group:add_moderator' username=user.username name=group_name %}" group-name="{{group_name}}" user-username="{{user.username}}">
                          <a href="#" class="group-moderate-management-btn hvr-grow" >
                            <i class="fa fa-check green-color" ></i>
                          </a>
                        </div>
                        <div action-url="{% url 'api-group:remove_demand_moderate' username=user.username name=group_name %}" group-name="{{group_name}}" user-username="{{user.username}}">
                          <a href="#" class="group-moderate-management-btn hvr-grow" >
                            <i class="fa fa-trash red-color" ></i>
                         </a>
                        </div>
                      </div>
                    </div>
                </li>
              {% endfor %}

          </ul>
        </div>





      </div>

    </div>
  </div>
</div>

rci/templates/group/group_detail.html
{% extends "base.html" %}


{% block page_title %} {{block.super}} {{object.name}}{% endblock page_title %}

{% block title %}Accueil{% endblock title %}

{% block ajax_script %}

  <script> //Must load ajax_list_functions.js

  $(document).on("ready",function(){ // when the document is fully loaded do the lambda expression

    var selectGroup   = $('#post-form').find('select');
    var postContainer = $('#post-container');
    var fetchDataUrl  = postContainer.attr("fetch-post-url");
    var postDataUrl   = postContainer.attr("create-post-url");
    var grouName      = postContainer.attr("group-name");
    var groupId       = postContainer.attr("group-id");
    selectGroup.val(groupId); selectGroup.hide();
    initAjaxListVariables('post-container', fetchDataUrl, postDataUrl); // init list variables
    initAjaxGroupVariables(groupName,DisplayMode='group-display'); // init group variables
    initPostListDisplay(); //Fetch posts and display them
    setPostFormRemainingChars();
    listenToGroup();
    setPostCreateDisplay();
  });

  </script>



{% endblock ajax_script %}
{% block content %}
  {% if request.user.profile in object.get_members %}

    <div class="row">
      <div class="col-sm-3 col-sm-offset-1">
        <h1> {{object}} </h1>
        <b> Desctiption: </b> </br>
        <p> {{object.description}} </p>



        <div class="dropdown">
          <a href="" class="dropdown-toggle transparent-btn hvr-overline-from-left" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Modérateurs du groupe</a>
          <ul class="dropdown-menu">
            {% for moderator in object.get_moderators %}
              <li>
                <a class=" " href="{{moderator.profile.get_absolute_url}}"> {{moderator}}
                <!-- <i class="pull-right fa fa-chevron-circle-right hvr-icon"></i> -->
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </br>
      {% if request.user not in object.get_moderators and request.user not in object.get_moderators_asks%}
        <div action-url="{% url 'api-group:demand_moderate' username=request.user.username name=object.name %}" group-name="{{object.name}}" user-username="{{request.user.username}}">
          <a href="#" type="group-demand-access" class="transparent-btn hvr-overline-from-left group-moderate-management-btn"> Devenir modérateur</a>
        </div>
      {% endif %}
      </div>
      <div class="col-sm-6">
        {% if not request.GET.q %}
            {% if request.user.profile in object.get_members %}

              <div class="">
                {% include 'post/form.html' with action_url=create_post_url form=post_form submit_value="Publier" form_class="post_form_class" %}
              </div>
            {% endif %}
        {% else %}
        <div class="">
          <h5>Research results:</h5>
        </div>
        {% endif %}
      </div>

    </div>
    <hr/>
    <div class="row">
      <div class="col-sm-2 col-sm-offset-1">

      </br>

      <div class="list-group">
        {% if request.user in object.get_moderators%}
          {% if object.get_join_asks %}
          <a class="  list-group-item" id='show-members-request-btn' href="#" >Demandes<span class="badge blue-back-color"> {{object.get_join_asks.count}} </span>
          </a>
          {% endif %}
          {% if object.get_moderators_asks %}
          <a class="  list-group-item" id='show-moderators-request-btn' href="#" >Demandes de modération<span class="badge blue-back-color"> {{object.get_moderators_asks.count}} </span>
          </a>
          {% endif %}
        {% endif %}
        <!-- <li class="list-group-item"> -->
          <a class="  list-group-item" id='show-members-btn' href="#" > Membres du groupe</a>
        <!-- </li> -->
    </div>

      </div>
      <div class="media col-sm-8 ">
        <div class="media-body" >
          <p id="post-container"
                  class        ='wrap-text'
                  fetch-post-url ="{{fetch_post_url}}"
                  create-post-url="{{create_post_url}}"
                  group-name   ="{{object.name}}"
                  group-id     = "{{object.pk}}">

          </p>
        </div>
      </div>
    </div>

  {% else %}
    <h3 style="text-align:center"> <i class='fa fa-ban fa-5x'></i> Vous n'avez pas le droit de visualiser ce contenu </h3>
    </br>
    </br>

    </br>
    </br>
    </br>
    <div action-url="{% url 'api-group:demand' username=request.user.username name=object.name %}" group-name="{{object.name}}" user-username="{{request.user.username}}" class="col-sm-5 col-sm-offset-2">

      <h5> Veuillez demander à être ajouté ou groupe pour pouvoir y accéder </h5>
      <a href="#" type="group-demand-access" class="group-access-management-btn link-btn hvr-float"> Demande
        <i class='fa fa-user-plus'></i>
      </a> d'ajout au groupe {{object.name}}
    </div>
    </br>
    </br>
    </br>
    </br>
  {% endif %}

  {% include 'group/group_members_modal.html' with request_user=request.user group_moderators=object.get_moderators group_members=object.get_members group_name=object.name %}
  {% include 'group/group_ask_join_modal.html' with request_user=request.user group_join_asks=object.get_join_asks group_name=object.name %}
  {% include 'group/group_ask_moderate_modal.html' with request_user=request.user group_moderators_asks=object.get_moderators_asks group_name=object.name %}
  

{% endblock content %}

rci/templates/group/group_members_modal.html
<div class="modal fade" id="members-modal"
 tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h5 class="modal-title" id="reply-form-header">Membres du groupe {{group_name}} :</h5>
          <hr>
        </div>

        <div class="modal-body">
          <ul class="list-group scroll-list">
              </h4> Membres: </h4>
              </br></br>
              {% for profile in group_members %}
                <li class="list-group-item">
                    <div class="row">
                      <div class="col-sm-2 ">
                        <a href = "{{profile.get_absolute_url}}">
                          <div class="row">
                          		<div class="profile-header-img col-sm-2 ">
                                <img class="img-min" src="{{profile.get_img_url}}" />

                              </div>
                          </div>
                        </a>
                      </div>
                      <div class="col-sm-2 in-line">
                        <div action-url="{% url 'api-group:remove_user' username=profile.user.username name=object.name %}" group-name="{{object.name}}" user-username="{{profile.user.username}}">
                          <a  href="{{profile.get_absolute_url}}">
                            {{profile}}
                          </a>
                          {% if request_user in group_moderators and profile.user not in group_moderators%}
                            <a href="#" class="group-access-management-btn top-left-corner hvr-grow">
                              <i class="fa fa-remove red-color" ></i>
                            </a>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                </li>
              {% endfor %}

          </ul>
        </div>





      </div>

    </div>
  </div>
</div>