account/api/urls.py
from django.urls import path

from .views import (
                ProfileListAPIView,
                ProfileLastVisitAPIView
                )


app_name    = 'api-profile'

urlpatterns = [
    path('list/', ProfileListAPIView.as_view(), name='list'),#/api/profile/list
    path('last_visit/', ProfileLastVisitAPIView.as_view(), name='last_visit')#/api/profile/last_visit
]

post/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
                PostDeleteView,
                PostDetailView,
                PostListView,
                PostCreateView,
                PostUpdateView
                )

app_name    = 'post'

urlpatterns = [
    path('list/', RedirectView.as_view(url='/home'), name='list'),#/
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),#/post/detail
    path('<int:pk>/update', PostUpdateView.as_view(), name='update'),#/post/update
    path('<int:pk>/delete', PostDeleteView.as_view(), name='delete'),#/post/delete
    path('create/', PostCreateView.as_view(), name='create'),#/post/create
]

rci/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from .views import home_view, SearchView
from account.views import UserRegisterView
from post.views import PostListView

urlpatterns = [
    path('', home_view, name='home'),
    path('home/', PostListView.as_view(), name='post-list'),
    path('admin/', admin.site.urls),
    path('search/', SearchView.as_view(), name="search"),
    path('register/', UserRegisterView.as_view(), name="register"),
    path('post/', include('post.urls', namespace='post')),
    path('profile/', include('account.urls', namespace='profile')),
    path('group/', include('group.urls', namespace='group')),
    path('tag/', include('hashtag.urls', namespace='hashtag')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('api/post/',include('post.api.urls', namespace='api-post')),
    path('api/profile/',include('account.api.urls', namespace='api-profile')),
    path('api/group/',include('group.api.urls', namespace='api-group')),
    path('api/comment/',include('comment.api.urls', namespace='api-comment')),
    path('', include('django.contrib.auth.urls')),

    # path('api/hashtag/',include('hashtag.api.urls', namespace='api-hashtag')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rci/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, reverse
from django.views import View

from group.models import Group
from hashtag.models import Hashtag

User = get_user_model()

def home_view(request):

    return render(request,"home.html",{})
    # return render(request,"home.html",context)

class SearchView(LoginRequiredMixin, View):
    login_url   = '/login'
    def get(self, request, *args, **kwargs):
        query                   = request.GET.get("q")
        users_queryset    = None
        if query is not None:
            users_queryset    = User.objects.filter(
                                Q(username__icontains=query)
                                )
        groups_queryset    = None
        if query is not None:
            groups_queryset    = Group.objects.filter(
                                Q(name__icontains=query)
                                )
        hashtags_queryset    = None
        if query is not None:
            hashtags_queryset  = Hashtag.objects.filter(
                                Q(tag__icontains=query)
                                )

        context = {
            "users"                 : users_queryset,
            "groups"                : groups_queryset,
            "tags"                  : hashtags_queryset,
            "fetch_post_url"        : reverse("api-post:list"),
            }
        return render(request, "search.html", context)

rci/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head class="settings"
                  static-url = "{% static '' %}"
                  request-user="{{request.user}}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'bootstrap/css/sidebar.css' %}" >
    <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'hover-css/hover-min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/base_view.css' %}" >
    <link href="{%static '/home_components/img/favicon.png'%}" rel="icon">

    <title>{% block page_title %}RCI | {% endblock page_title %}</title>
    <style>



    </style>

  </head>
  <body>

    {% include "navbar.html" %}
    </br>
    <div id="rci-container" class="container-fluid ">
      <div id="general-container" class="container" >
        </br>
        {% block content %}
        {% endblock content %}
      </div>
    </div>
      {% include 'message_box.html' %}
      {% include 'message_box_confirmation.html' %}
    <div id="rci-about">
      <p>

      </p>
    </div>
    <a href="#" style="display:none;"class="stuck back-to-top"><i class=" white-color pull-right  fa fa-chevron-up hvr-float fa-3x"></i></a>

    <section id="contact">

      <!-- <div id="google-map" data-latitude="36.7683668" data-longitude="3.012260"></div> -->

      <div class="wow fadeInUp">
        <div class="row justify-content-center ">
          <div class="container-contact-us ">
            <div class="row text-center">
              <div class="center-div">
                <h3 class="section-title">À propos</h3>
              </div>
            </div>
            <div class="row">
              <div class="center-div">
                <div class="col-sm-4">
                  <h3 class="section-title">Contactez nous</h3>
                  <p class="section-description"></p>
                  <div class="info">
                    <div>
                      <i class="fa fa-map-marker"></i>
                      <span>Alger, Ben Aknoun</span></br></br>
                    </div>

                    <div>
                      <i class="fa fa-envelope"></i>
                      <span>email@rci.com</span></br></br>
                    </div>

                    <div>
                      <i class="fa fa-phone"></i>
                      <span>+213 000 000 000</span></br></br>
                    </div>
                  </div>

                  <div class="social-links">
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
                <div class="col-sm-4 col-sm-offset-4">
                  <h3 class="section-title">Voir aussi</h3>
                  <p class="section-description"></p>
                  <div class="info">
                    <div>
                      <i class="fa fa-code"></i>
                      <a class="link-about-us" href="#">Code source</a></br></br>
                    </div>

                    <div>
                      <i class="fa fa-building"></i>
                      <a class="link-about-us" href="#">le site de l'entreprise</a></br></br>
                    </div>


                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- #contact -->

    {% include "post/post_img_modal.html" %}
    {% include "post/post_file_modal.html" %}

    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'script/extra.js' %}"></script>
    <script src="{% static 'script/ajax_list_functions.js' %}"></script>
    <script src="{% static 'script/ajax_post_functions.js' %}"></script>
    <script src="{% static 'script/ajax_group_functions.js' %}"></script>
    <script src="{% static 'script/ajax_account_functions.js' %}"></script>
    <script src="{% static 'script/search.js' %}"></script>
    <script src="{% static 'script/base_view.js' %}"></script>
    {% block ajax_script %}
    {% endblock ajax_script %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

rci/templates/message_box.html
<div class="modal fade" id="message-box"
 tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="box-title"></h5>
          <div>
            <em id="message-box-message">
            </em>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

rci/templates/message_box_confirmation.html
<div class="modal fade" id="message-box-confirmation"
 tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="box-title"></h5>
          <div>
            <em id="message-box-message">
            </em>
            <input class="btn btn-primary" id="confirm-message-box" type="submit" value="Confirmer"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

rci/templates/navbar.html
<nav class="navbar navbar-default center-97" id="rci-navbar" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{%url 'post-list'%}">RCI</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    {% if request.user.is_authenticated %}
      {% include "search_bar.html" %}
    {% endif %}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{request.user.profile.get_absolute_url}}"><i class='fa fa-user'></i>  Profile</a></li>
            <li><a href="{%url 'profile:update'%}"><i class='fa fa-edit'></i>  Modifier mon compte</a></li>
            <li><a id="logout-btn" last-visit-url="{% url 'api-profile:last_visit' %}" href="{% url 'logout' %}"><i class='fa fa-sign-out'></i>  Se déconnecter</a></li>

            {% if request.user.is_staff %}
            <li role="separator" class="divider"></li>
              <li><a href="/admin/"><i class='fa fa-unlock-alt'></i>  Administrer</a></li>
            {% endif %}

          </ul>
        </li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'login' %}">Se connecter</a></li>
          <li><a href="{% url 'register' %}">S'enregistrer</a></li>
      </ul>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rci/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block page_title %} {{block.super}} Recherche{% endblock page_title %}

{% block title %}Search{% endblock title %}

{% block ajax_script %}

  <script> //Must load list_tweet.js

  $(document).on("ready",function(event){
    $(".search-content").hide();
    $("#post-content").show();

    var fetchDataUrl  = $('#post-container').attr("get-data-url");

    initAjaxListVariables('post-container', fetchDataUrl); //| from ajax_list_functions.js |  init variables
    initPostListDisplay(); // | from ajax_post_functions.js | Fetch posts and display them
    listenToSearches();


  })
  </script>



{% endblock ajax_script %}
{% block content %}

<style>
  .max-width{
    width=100%;
    height=auto;
  }
</style>

  <div class="row">
    <div class="col-sm-2">
      <div id="search-category-navbar" class="inline max-width">
          <!-- <div data-spy="affix"> -->
            <div class="max-width list-group ">
             <a class="active list-group-item">Catégories</a>
             <a id="profile-search-btn" class="list-group-item"href="#">Profils
               <span class="pull-right badge blue-back-color">{{users.count}}</span>
             </a>
             <a id="post-search-btn" href="#" class="list-group-item">Publications
               <span class="pull-right badge blue-back-color"> {{0}}</span>
             </a>
             <a id="hashtag-search-btn" href="#" class="list-group-item">Hashtags
               <span class="pull-right badge blue-back-color">{{tags.count}}</span>
             </a>
             <a id="group-search-btn" href="#" class="list-group-item">Groupes
               <span class="pull-right badge blue-back-color">{{groups.count}}</span>
             </a>
            </div>
          <!-- </div> -->
      </div>
    </div>
    <div class="col-sm-10 ">
      <div class="row">
        <div class="col-sm-7 col-sm-offset-1 ">
          {% if request.GET.q %}
            <p class="lead"> Résultats pour : {{request.GET.q}} </p>
          {% endif %}
        </div>
      </div>
    <hr/>

      <div class="row">
        <div id="post-content" class="media col-sm-10 search-content">
          <div class="media-body">
            <h1> Publications : </h1>
            <hr/>
            <p id="post-container"
                    class='wrap-text'
                    get-data-url="{{fetch_post_url}}">

            </p>
          </div>
        </div>
        <div id="group-content" class = "col-sm-8 col-sm-offset-1 search-content">
            <h1> Groupes : </h1>
            <hr class="right-solid"/>
            {% for group in groups %}
            <a style="text-align:right;" href="{{group.get_absolute_url}}"> {{group.name}}: </a>
            <p>{{group.description}}
            </p>
            <hr class="right-solid">
            {% empty %}
            <h4> Aucun group trouvé. </h4>
            {% endfor %}
        </div>
        <div id="user-content" class = "col-sm-10 search-content">
            <h1> Profils : </h1>
            <hr class="right-solid"/>
            {% for user in users %}
            <div class="row">
              <div class="col-sm-3">
                <a href = "{{user.profile.get_absolute_url}}">
                  <div class="row">
                    <div class="profile-header-container">
                  		<div class="profile-header-img col-sm-2 ">
                        <img class="img-circle" src="{{user.profile.get_img_url}}" />
                        <div class="rank-label-container">
                          <span class="label label-default rank-label"> {{user.username}} </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="col-sm-5">
                <a style="text-align:right;" href="{{user.profile.get_absolute_url}}"> {{user.username}} </a>
                <p>
                  Nom    : {{user.last_name}}</br>
                  Prénom : {{user.first_name}}</br>
                  Statut : {{user.profile.status}}</br>
                  E-mail : {{user.email}}</br>
                </p>
              </div>
            </div>
            <hr class="right-solid">

            {% empty %}
            <h4> Aucun utilisateur trouvé. </h4>
            {% endfor %}
        </div>
        <div id="hashtag-content" class = "col-sm-10 search-content">
            <h1> Hashtags : </h1>
            <hr class="right-solid"/>
            {% for tag in tags %}
            <a style="text-align:right;" href="{{tag.get_absolute_url}}"> #{{tag.tag}} </a>
            <hr class="right-solid">
            {% empty %}
            <h4> Aucun hashtag trouvé. </h4>
            {% endfor %}
        </div>
      </div>

    </div>

  </div>


  </br></br>
{% endblock content %}

rci/templates/search_bar.html
<form id='search_form' class="navbar-form navbar-left" method="get" action="{% url 'search' %}">

  <div class="form-group">
    <!-- <label for="q"> Search </label> -->
    <input id='search_input' type="text" name="q" value="{{request.GET.q}}" class="form-control"  placeholder="Votre recherche">
  </div>


  <button id="submit-search-btn" type="submit" class="btn btn-default">Chercher <i class='fa fa-search '></i></button>
</form>